Constructor-io/constructorio-client-swift

AutocompleteClient.xcodeproj/project.pbxproj
AutocompleteClient.xcodeproj/xcshareddata/xcschemes/AutocompleteClient.xcscheme
AutocompleteClient/FW/API/Parser/CIOResponseParser.swift
AutocompleteClient/FW/API/Parser/ResponseParserDelegate.swift
AutocompleteClient/FW/Logic/Highlighting/Attributes/BoldAttributesProvider.swift
AutocompleteClient/FW/Logic/Highlighting/CIOHighlighter.swift
AutocompleteClient/FW/UI/CIOAutocompleteViewController.swift
AutocompleteClient/FW/UI/DefaultSearchItemCell.swift
AutocompleteClient/FW/UI/Delegate/CIOAutocompleteDelegate.swift
AutocompleteClient/Utils/Collection/Collection+MapKeys.swift
AutocompleteClientTests/Logic/Highlighting/CIOHighlighterTests.swift
AutocompleteClientTests/Logic/Result/MockResponseParserDelegate.swift
AutocompleteClientTests/Logic/Result/ResultParserTests.swift
UserApplication/AppDelegate.swift

Implemented section filtering. User can now filter sections simply by implementing the following delegate method
`func autocompleteController(controller: CIOAutocompleteViewController, shouldParseResultsInSection sectionName: String) -> Bool`

Section filtering

---

AutocompleteClient/Constants/Constants.swift
AutocompleteClient/FW/Logic/Query/Builder/RequestBuilder.swift
AutocompleteClient/FW/Logic/Query/Builder/TrackAutocompleteClickRequestBuilder.swift
AutocompleteClientTests/Logic/Query/Builder/TrackAutocompleteClickRequestBuilderTests.swift
AutocompleteClientTests/Logic/Query/Builder/TrackConversionRequestBuilderTests.swift

- Moved _dt constant to Track constants structure.
- Moved adding date query item from the TrackAutocompleteClickRequestBuilder to the superclass.
- Added track conversion test assertions that test whether the request contains the current date. We're pulling the date from the url.components which is perfectly fine. I've created a dateProvider property inside the RequestBuilder so we can test whether the dates match, but I don't think that's a priority atm.

Datetime _dt parameter is now attached to every request

---

AutocompleteClient/FW/API/Parser/CIOResponseParser.swift
AutocompleteClient/FW/API/Parser/ResponseParserDelegate.swift
AutocompleteClient/FW/UI/CIOAutocompleteViewController.swift
AutocompleteClient/FW/UI/Delegate/CIOAutocompleteDelegate.swift
AutocompleteClientTests/Logic/Result/MockResponseParserDelegate.swift
AutocompleteClientTests/Logic/Result/ResultParserTests.swift
UserApplication/AppDelegate.swift

One test has been deleted. It was testing the logic of number of parsed group items being returned. We now allow for customization of this parameter, therefore this test can go.

Implemented delegate method that allow customization of number of group items to be displayed

---

AutocompleteClient.xcodeproj/project.pbxproj
AutocompleteClient/FW/Logic/Conversion/CIOTracker.swift
AutocompleteClient/FW/Logic/Conversion/CIOTracking.swift
AutocompleteClient/FW/Logic/Query/Builder/TrackAutocompleteClickRequestBuilder.swift
AutocompleteClient/FW/Logic/Query/Builder/TrackConversionRequestBuilder.swift
AutocompleteClient/FW/Logic/Query/Builder/TrackInputFocusRequestBuilder.swift
AutocompleteClient/FW/Logic/Query/Builder/TrackSearchRequestBuilder.swift
AutocompleteClient/FW/Logic/Query/Builder/TrackSearchResultsLoadedRequestBuilder.swift
AutocompleteClient/FW/Logic/Query/Builder/TrackSessionStartRequestBuilder.swift
AutocompleteClient/FW/Logic/Track/CIOTrackAutocompleteClickData.swift
AutocompleteClient/FW/Logic/Track/CIOTrackConversionData.swift
AutocompleteClient/FW/Logic/Track/CIOTrackInputFocusData.swift
AutocompleteClient/FW/Logic/Track/CIOTrackSearchData.swift
AutocompleteClient/FW/Logic/Track/CIOTrackSearchResultsLoadedData.swift
AutocompleteClient/FW/Logic/Worker/ConstructorIO.swift
AutocompleteClient/FW/UI/CIOAutocompleteViewController.swift
AutocompleteClientTests/Logic/Query/Builder/TrackAutocompleteClickRequestBuilderTests.swift
AutocompleteClientTests/Logic/Query/Builder/TrackConversionRequestBuilderTests.swift
UserApplication/DetailsViewController.swift

Tracking naming cleanup/consistency

---

AutocompleteClient/FW/API/Data/TaskResponse.swift
AutocompleteClient/FW/Logic/Track/HasSectionName.swift

- TaskResponse properties should be public so they're accessible from outside the framework.
- Fixed HasSectionName file header.

Changed TaskResponse properties scope to public

---

AutocompleteClient/Constants/Constants.swift
AutocompleteClient/FW/Logic/Request/Builder/QueryItemCollection.swift
AutocompleteClient/FW/Logic/Request/Builder/RequestBuilder+QueryItems.swift
AutocompleteClient/FW/Logic/Request/CIOTrackConversionData.swift
AutocompleteClient/FW/Logic/Request/CIOTrackRecommendationResultsViewData.swift
AutocompleteClient/FW/Logic/Result/CIOResult.swift
AutocompleteClient/FW/Logic/Worker/ConstructorIO.swift
AutocompleteClientTests/FW/Logic/Request/TrackConversionRequestBuilderTests.swift
AutocompleteClientTests/FW/Logic/Request/TrackPurchaseRequestBuilderTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOTrackConversionTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOTrackRecommendationResultsViewTests.swift
README.md

- Pass type in request body
- v2 endpoint expects revenue as String
- Taking it in as a double to conform with other method and converting it into string
- Added and updated tests
- Update readme
- Add custom_type and display_name in later PR

[CSL 6] Handle Conversion Types with v2

---

AutocompleteClient/FW/Logic/Request/CIOAutocompleteQuery.swift
AutocompleteClientTests/FW/Logic/Request/AutocompleteQueryRequestBuilderTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOAutocompleteTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift

* Add support for filtering in autocomplete requests
* Add integration tests for Browse, Search and Autocomplete
* Fix some lint issues
* Autocomplete requests only accepts 1 filter at the moment and returns an error if more than 1 is supplied:
* `Error Code 400: Bad Request - Your request is invalid.` which doesn't seem very helpful? 🤔 
* The error that comes back from the server is `Only single filters are supported in autocomplete, but you seem to have provided more than one.`, but it doesn't seem to show up in the response object in Swift. It looks like all that information is being stripped away, but I don't understand Swift enough to figure out where/how that's happening
* I guess they can reference the API doc to figure out why.. but that kind of sucks to need to do that...

[CSL 395] Add Filtering to Autocomplete Requests

---

AutocompleteClient.xcodeproj/project.pbxproj
AutocompleteClient/FW/API/Parser/Autocomplete/ResponseParserDelegate.swift
AutocompleteClient/FW/Logic/Session/CIOSessionManagerDelegate.swift
AutocompleteClient/FW/Logic/Session/SessionManager.swift
AutocompleteClient/FW/UI/Delegate/CIOAutocompleteDelegate.swift
AutocompleteClient/FW/UI/Error/CIOErrorView.swift
AutocompleteClient/FW/UI/UICustomization/CIOAutocompleteUICustomization.swift
AutocompleteClient/FW/UI/ViewModel/AutocompleteViewModelDelegate.swift
ConstructorAutocomplete.podspec
UserApplication/AppDelegate.swift

* Add swift v5.0 to list of swift versions
* Fix lint warnings
* I ran the user application tests and made some small updates to the dependencies and minor change to a test
* One of the user application tests doesn't seem to work and I'm not sure why (or if it's something we need to care about 🤔 )

[CSL 573] Pod Spec Lint Fixes

---

AutocompleteClient.xcodeproj/project.pbxproj
AutocompleteClient/FW/Logic/Request/Builder/CIOBrowseQueryBuilder.swift
AutocompleteClient/FW/Logic/Request/Builder/CIOSearchQueryBuilder.swift
AutocompleteClient/FW/Logic/Request/Builder/RequestBuilder+QueryItems.swift
AutocompleteClient/FW/Logic/Request/CIOBrowseQuery.swift
AutocompleteClient/FW/Logic/Request/CIOGroupsSortOption.swift
AutocompleteClient/FW/Logic/Request/CIOSearchQuery.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOBrowseTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOSearchTests.swift
README.md

* Add support for groups sort format option + tests
* `fmt_options[groups_sort_by]`
* Possible values are `relevance`, `num_matches` or `value`.
* `fmt_options[groups_sort_order]`
* Possible values are `ascending` or `descending`.

[CSL 1382] Add support for groups sort option + tests

---

AutocompleteClient/FW/Logic/Result/CIOFilterGroup.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift

* Resolves issue with parent groups not being returned in client responses due to parent groups not containing a count property causing nil to be returned during deserialization
* Added two new tests to check for parents and children for search/browse (All tests pass, except for a hidden field one which is a separate issue)

[CSL 1424] Fix parent groups

---

AutocompleteClient.xcodeproj/project.pbxproj
AutocompleteClient/Constants/Constants.swift
AutocompleteClient/FW/Logic/Request/Builder/CIOSearchQueryBuilder.swift
AutocompleteClient/FW/Logic/Request/Builder/RequestBuilder+QueryItems.swift
AutocompleteClient/FW/Logic/Request/CIOTrackBrowseResultClickData.swift
AutocompleteClient/FW/Logic/Request/CIOTrackConversionData.swift
AutocompleteClient/FW/Logic/Request/CIOTrackSearchResultClickData.swift
AutocompleteClient/FW/Logic/Worker/ConstructorIO.swift
AutocompleteClientTests/FW/Logic/Request/TrackBrowseResultClickRequestBuilder.swift
AutocompleteClientTests/FW/Logic/Request/TrackConversionRequestBuilderTests.swift
AutocompleteClientTests/FW/Logic/Request/TrackSearchResultClickRequestBuilder.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOTrackBrowseResultClickTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOTrackConversionTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOTrackSearchResultClickTests.swift
README.md

* Add variation ids to all behavioral events that support it (already supported in recommendation result click)
* Browse Result Click
* Search Result Click
* Conversion
* Add/Update tests (all tests pass)
* Update README examples
Separate PR for purchase events: https://github.com/Constructor-io/constructorio-client-swift/pull/148

[CSL 1565] Add support for variation ids in behavioral events

---

AutocompleteClient.xcodeproj/project.pbxproj
AutocompleteClient/FW/Logic/Request/CIOItem.swift
AutocompleteClient/FW/Logic/Request/CIOPurchaseItem.swift
AutocompleteClient/FW/Logic/Request/CIOSearchQuery.swift
AutocompleteClient/FW/Logic/Request/CIOTrackPurchaseData.swift
AutocompleteClient/FW/Logic/Worker/ConstructorIO.swift
AutocompleteClientTests/FW/Logic/Request/TrackPurchaseRequestBuilderTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift
README.md

* Add new `CIOItem` struct
* Overloaded `trackPurchase` function to accept a list of `CIOItem`s
* Overloaded `trackPurchaseData`'s init function to accept a list of `CIOItem`s
* Changing `customerIDs` and `items` fields to be optional so you can pass either isn't super great. Makes it possible to send purchase events w/o items
* Add support for quantity
* Add/update tests (all tests pass)

[CSL 1565] Support variation ids in purchase events

---

AutocompleteClient/FW/Logic/Result/CIOQuizOption.swift
AutocompleteClient/FW/Logic/Result/CIOQuizQuestion.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOQuizIntegrationTests.swift

* Update to point tests to new request tests index
* Minor fixes to Quiz classes that was causing issues and returning nil for the entire object rather than individual fields
* All tests pass! 🎊 
* https://github.com/Constructor-io/integration-examples/pull/4

[CSL 1825] Point tests to new index & minor fixes

---

AutocompleteClient/FW/Logic/Request/Builder/QueryItemCollection.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift

Deleting the "us" parameter from http body. 
Api expects the format as a list, but our logic right now doesn't handle that. 
Instead of changing the logic, I am removing the "us" parameter from the httpbody.

[CSL-2352] Update query items logic.

---

AutocompleteClient/FW/Logic/Request/CIOTrackPurchaseData.swift
AutocompleteClientTests/FW/Logic/Request/TrackPurchaseRequestBuilderTests.swift

When creating the HTTP Body to be used for the Purchase Tracking Event, round the revenue down to 2 decimal places.

[CSL-2362] Rounds revenue to 2dp in purchase tracking event

---

AutocompleteClient/FW/Logic/Worker/ConstructorIO.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOABTestCellTests.swift

Empty test cell values will cause the api to throw 400. This prevent those empty values from being sent.

[NOCSL] Don't send empty test cell

---

AutocompleteClient/Constants/Constants.swift
AutocompleteClient/FW/API/Parser/Quizzes/QuizQuestionResponseParser.swift
AutocompleteClient/FW/API/Parser/Quizzes/QuizResultsResponseParser.swift
AutocompleteClient/FW/Logic/Request/Builder/RequestBuilder+QueryItems.swift
AutocompleteClient/FW/Logic/Request/CIOQuizQuery.swift
AutocompleteClient/FW/Logic/Result/Responses/CIOQuizQuestionResponse.swift
AutocompleteClient/FW/Logic/Result/Responses/CIOQuizResultsResponse.swift
AutocompleteClient/FW/Logic/Worker/ConstructorIO.swift
AutocompleteClientTests/FW/Logic/Request/QuizzesQueryRequestBuilderTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOQuizIntegrationTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOQuizTests.swift
README.md

The rest of the repository largely follows the convention `<variable>ID`. This PR makes Quizzes-related methods consistent w/ the rest of the repo.
Note: As I was doing this story, I also noted other instances where we do `<variable>Id` instead of `<variable>ID`
- browseGroups - `groupId`
- CIOResultData - `variationId`
Since these might already be in use, it might require additional lift and discussion to make backwards compatible.

[CSL-2781] Use ID instead of Id for attribute/variable names for Quizzes-related methods

---

AutocompleteClient/FW/Logic/Request/CIOTrackBrowseResultsLoadedData.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOTrackBrowseResultsLoadedTests.swift

* Made update to the code and updated some of the tests
* Our server was throwing a 4XX error as our client was passing `resultID` instead of `result_id` in trackBrowseResultsLoaded

Fix issue with resultID in browse result loaded event

---

AutocompleteClient/FW/Logic/Worker/ConstructorIO.swift

Before
- group: Item group (if present)
After
- group: The group to search within if a user elected to search in a group, i.e. "Pumpkin in Canned Goods" (if present)
Changed in 
- trackAutocompleteSelect
- trackSearchSubmit

Update search events group Id documentation

---

AutocompleteClientTests/FW/API/Parser/BrowseResponseParserTest.swift
AutocompleteClientTests/FW/API/Parser/SearchResponseParserTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOIntegrationTests.swift

* With the recent xcodebuild update to 16.2, it looks like our tests that are using force casting are causing the builds to fail, this fixes that issue
* [Setting up and running the Swift repo](https://constructor.slab.com/posts/setting-up-and-running-the-i-os-swift-repository-ry475ixw)

Update failing tests due to force cast

---

AutocompleteClient/FW/Logic/Request/Builder/CIOBrowseItemsQueryBuilder.swift
AutocompleteClient/FW/Logic/Request/Builder/CIOBrowseQueryBuilder.swift
AutocompleteClient/FW/Logic/Request/Builder/CIOSearchQueryBuilder.swift
AutocompleteClient/FW/Logic/Request/CIOBrowseItemsQuery.swift
AutocompleteClient/FW/Logic/Request/CIOBrowseQuery.swift
AutocompleteClient/FW/Logic/Request/CIOSearchQuery.swift
AutocompleteClient/FW/Logic/Result/CIOFilterFacet.swift
AutocompleteClientTests/FW/Logic/Request/TrackSearchResultClickRequestBuilder.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOBrowseItemsTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOBrowseTests.swift
AutocompleteClientTests/FW/Logic/Worker/ConstructorIOSearchTests.swift

- There are cases where the response returns min and max not as integers. Example:
```
{
"display_name": "price_amount",
"name": "price_amount",
"data": {},
"type": "range",
"hidden": false,
"status": {},
"min": 10.22,
"max": 99.9
}
```
- The current initializer nullifies out min and max if they are not integers, finally resulting in min and max always equal to zero.
- Suggestion: to keep the interface of min and max as integers, first cast them as? Double, then cast to Int using the `floor` value for min and `ceil` value for max.

CIOFilterFacet - Fix cases when min and max are returned as Double in the response
